// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqwcldifixceowhbwnyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlxd2NsZGlmaXhjZW93aGJ3bnlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NjQ0NzksImV4cCI6MjA3MjU0MDQ3OX0.XTRxf6FfhJOJt6oygj7T9V6-XHE5XkoDrxXf_2OFVPk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});